service: serverless-starter

provider:
  name: aws
  runtime: nodejs4.3

plugins:
  - serverless-offline

functions:
  registration:
    handler: build/registration.handler
    events:
      - cognitoUserPool:
          pool: MyUserPool
          trigger: PreSignUp
